package edu.caltech.nanodb.qeval;


import edu.caltech.nanodb.relations.Tuple;


/**
 * This interface allows us to decouple the implementation of the query
 * evaluation loop from the operations performed on each tuple generated by the
 * evaluator.  Different commands can implement this interface in different ways
 * to perform various operations; for example, the <code>DELETE</code> command
 * can provide a processor that deletes each tuple produced by the query
 * evaluation.
 */
public interface TupleProcessor {
    /**
     * Processes a single tuple generated from evaluating a query plan.
     *
     * @param tuple The tuple to process.
     *
     * @throws Exception if any errors occur during tuple processing.
     */
    public void process(Tuple tuple) throws Exception;
}

