// $ANTLR 2.7.7 (20060906): "nanosql.g" -> "NanoSqlLexer.java"$

  /**
   * Copyright (c) 2005-2011 by the California Institute of Technology.
   * All rights reserved.
   **/
  package edu.caltech.nanodb.sqlparse;

  import java.util.ArrayList;
  import java.util.List;

  import edu.caltech.nanodb.commands.*;
  import edu.caltech.nanodb.expressions.*;
  import edu.caltech.nanodb.relations.*;

public interface NanoSqlParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int ADD = 4;
	int ALL = 5;
	int ALTER = 6;
	int ANALYZE = 7;
	int AND = 8;
	int ANY = 9;
	int AS = 10;
	int AVG = 11;
	int BETWEEN = 12;
	int COLUMN = 13;
	int CONSTRAINT = 14;
	int COUNT = 15;
	int CREATE = 16;
	int CROSS = 17;
	int DEFAULT = 18;
	int DELETE = 19;
	int DISTINCT = 20;
	int DROP = 21;
	int EXISTS = 22;
	int EXIT = 23;
	int EXPLAIN = 24;
	int FALSE = 25;
	int FOREIGN = 26;
	int FROM = 27;
	int FULL = 28;
	int IF = 29;
	int IN = 30;
	int INDEX = 31;
	int INNER = 32;
	int INSERT = 33;
	int INTO = 34;
	int IS = 35;
	int JOIN = 36;
	int KEY = 37;
	int LEFT = 38;
	int LIKE = 39;
	int MAX = 40;
	int MIN = 41;
	int NATURAL = 42;
	int NOT = 43;
	int NULL = 44;
	int ON = 45;
	int OR = 46;
	int OUTER = 47;
	int PRIMARY = 48;
	int QUIT = 49;
	int REFERENCES = 50;
	int RENAME = 51;
	int RIGHT = 52;
	int SELECT = 53;
	int SET = 54;
	int SOME = 55;
	int STDDEV = 56;
	int SUM = 57;
	int TABLE = 58;
	int TO = 59;
	int TRUE = 60;
	int UNIQUE = 61;
	int UNKNOWN = 62;
	int UPDATE = 63;
	int USING = 64;
	int VALUES = 65;
	int VARIANCE = 66;
	int VIEW = 67;
	int WHERE = 68;
	int TYPE_BIGINT = 69;
	int TYPE_BLOB = 70;
	int TYPE_CHAR = 71;
	int TYPE_CHARACTER = 72;
	int TYPE_DATE = 73;
	int TYPE_DATETIME = 74;
	int TYPE_DECIMAL = 75;
	int TYPE_FLOAT = 76;
	int TYPE_DOUBLE = 77;
	int TYPE_INT = 78;
	int TYPE_INTEGER = 79;
	int TYPE_NUMERIC = 80;
	int TYPE_TEXT = 81;
	int TYPE_TIME = 82;
	int TYPE_TIMESTAMP = 83;
	int TYPE_VARCHAR = 84;
	int TYPE_VARYING = 85;
	int INT_LITERAL = 86;
	int LONG_LITERAL = 87;
	int FLOAT_LITERAL = 88;
	int DEC_LITERAL = 89;
	int PERIOD = 90;
	int SEMICOLON = 91;
	int IDENT = 92;
	int QUOTED_IDENT = 93;
	int TEMPORARY = 94;
	int LPAREN = 95;
	int COMMA = 96;
	int RPAREN = 97;
	int GROUP = 98;
	int BY = 99;
	int HAVING = 100;
	int ORDER = 101;
	int STAR = 102;
	int EQUALS = 103;
	int NOT_EQUALS = 104;
	int GRTR_THAN = 105;
	int LESS_THAN = 106;
	int GRTR_EQUAL = 107;
	int LESS_EQUAL = 108;
	int PLUS = 109;
	int MINUS = 110;
	int SLASH = 111;
	int PERCENT = 112;
	int STRING_LITERAL = 113;
	int COLON = 114;
	int NEWLINE = 115;
	int WS = 116;
	int COMMENT = 117;
	int COMPARE_OPERATOR = 118;
	int NUM_LITERAL_OR_SYMBOL = 119;
}
