// $ANTLR 2.7.7 (20060906): "nanosql.g" -> "NanoSqlLexer.java"$

  /**
   * Copyright (c) 2005-2011 by the California Institute of Technology.
   * All rights reserved.
   **/
  package edu.caltech.nanodb.sqlparse;

  import java.util.ArrayList;
  import java.util.List;

  import edu.caltech.nanodb.commands.*;
  import edu.caltech.nanodb.expressions.*;
  import edu.caltech.nanodb.relations.*;

public interface NanoSqlParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int ADD = 4;
	int ALL = 5;
	int ALTER = 6;
	int ANALYZE = 7;
	int AND = 8;
	int ANY = 9;
	int AS = 10;
	int AVG = 11;
	int BETWEEN = 12;
	int COLUMN = 13;
	int CONSTRAINT = 14;
	int COUNT = 15;
	int CREATE = 16;
	int CROSS = 17;
	int DEFAULT = 18;
	int DELETE = 19;
	int DISTINCT = 20;
	int DROP = 21;
	int EXISTS = 22;
	int EXIT = 23;
	int EXPLAIN = 24;
	int FALSE = 25;
	int FOREIGN = 26;
	int FROM = 27;
	int FULL = 28;
	int IN = 29;
	int INDEX = 30;
	int INNER = 31;
	int INSERT = 32;
	int INTO = 33;
	int IS = 34;
	int JOIN = 35;
	int KEY = 36;
	int LEFT = 37;
	int LIKE = 38;
	int MAX = 39;
	int MIN = 40;
	int NATURAL = 41;
	int NOT = 42;
	int NULL = 43;
	int ON = 44;
	int OR = 45;
	int OUTER = 46;
	int PRIMARY = 47;
	int QUIT = 48;
	int REFERENCES = 49;
	int RENAME = 50;
	int RIGHT = 51;
	int SELECT = 52;
	int SET = 53;
	int SOME = 54;
	int STDDEV = 55;
	int SUM = 56;
	int TABLE = 57;
	int TO = 58;
	int TRUE = 59;
	int UNIQUE = 60;
	int UNKNOWN = 61;
	int UPDATE = 62;
	int USING = 63;
	int VALUES = 64;
	int VARIANCE = 65;
	int VIEW = 66;
	int WHERE = 67;
	int TYPE_BIGINT = 68;
	int TYPE_BLOB = 69;
	int TYPE_CHAR = 70;
	int TYPE_CHARACTER = 71;
	int TYPE_DATE = 72;
	int TYPE_DATETIME = 73;
	int TYPE_DECIMAL = 74;
	int TYPE_FLOAT = 75;
	int TYPE_DOUBLE = 76;
	int TYPE_INT = 77;
	int TYPE_INTEGER = 78;
	int TYPE_NUMERIC = 79;
	int TYPE_TEXT = 80;
	int TYPE_TIME = 81;
	int TYPE_TIMESTAMP = 82;
	int TYPE_VARCHAR = 83;
	int TYPE_VARYING = 84;
	int INT_LITERAL = 85;
	int LONG_LITERAL = 86;
	int FLOAT_LITERAL = 87;
	int DEC_LITERAL = 88;
	int PERIOD = 89;
	int SEMICOLON = 90;
	int IDENT = 91;
	int QUOTED_IDENT = 92;
	int LPAREN = 93;
	int COMMA = 94;
	int RPAREN = 95;
	int GROUP = 96;
	int BY = 97;
	int HAVING = 98;
	int ORDER = 99;
	int STAR = 100;
	int EQUALS = 101;
	int NOT_EQUALS = 102;
	int GRTR_THAN = 103;
	int LESS_THAN = 104;
	int GRTR_EQUAL = 105;
	int LESS_EQUAL = 106;
	int PLUS = 107;
	int MINUS = 108;
	int SLASH = 109;
	int PERCENT = 110;
	int STRING_LITERAL = 111;
	int COLON = 112;
	int NEWLINE = 113;
	int WS = 114;
	int COMMENT = 115;
	int COMPARE_OPERATOR = 116;
	int NUM_LITERAL_OR_SYMBOL = 117;
}
